# Generated by Django 5.2.15 on 2026-06-30 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='document_font',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
