# Generated by Django 5.2.15 on 2026-06-30 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_resume_document_font'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='section_order',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
