# Generated by Django 5.2.15 on 2026-06-20 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(choices=[('improve-bullet', 'Improve bullet'), ('generate-summary', 'Generate summary'), ('tailor-jd', 'Tailor to job description')], max_length=32)),
                ('input_length', models.PositiveIntegerField(default=0)),
                ('output_length', models.PositiveIntegerField(default=0)),
                ('success', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='ai_aiusagel_user_id_e34bca_idx')],
            },
        ),
    ]
