# Generated by Django 5.2.15 on 2026-06-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiusagelog',
            name='feature',
            field=models.CharField(choices=[('improve-bullet', 'Improve bullet'), ('generate-summary', 'Generate summary'), ('tailor-jd', 'Tailor to job description'), ('parse-resume', 'Parse résumé'), ('cover-letter', 'Cover letter'), ('ats-check', 'ATS health check')], max_length=32),
        ),
    ]
